server:
  port: 8081
  servlet:
    context-path: /
    session:
      timeout: 30m

jasypt:
  encryptor:
    password: REDLXIRGRETFD

SECRET_ID: ENC(LX+Dp8PemWOocmh63ZwpRi1zHipZzwTGIk1mzzGXWRGywDlA+6RRvBHuHyqZvzhzVcNOr6jPGKZy1SNoQRSwukBiNjoHGvBBQh1B073w0lU=)
SECRET_KEY: ENC(XOofR17e0jwbkvG6NUq8opazCBSg01OHjYZyD1RhpuEBpWAj5qm5dJzCKC2dWxXOo4rZGpIEIAF9hgIK6hTw5ztBfRhENZRQZbb91mXNUzQ=)

management:
  endpoint:
    web:
      exposure:
        include: health

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: ENC(pG1nrvXLMDrgUaSkzIMkWlcxQmhsDY6ONWSaTGRowOHfd4odpBvApftIotiafZ4vq3lSa4BMjkpHXepHZV44v4mgcJsyhEEnpkpHust+SGE=)
    username: ENC(//mZsqJl4h1VXp5tYIwnNC9rqPUIGJqAILJOYE5W+1usk0l/JbTMvvh7p0ldwhXv)
    password: T34X7i/AESfBBbvyrpRTCJFTY7gkpWqfKaPckRPySx80rg5nEZ7SIJgmM1EgXrzzv1UE5UUaytumgGkUZkpzkA==
    druid:
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJwC0siV5KntGBea3I7m0D5yTChgOn8GI+QB+2dcM2OShu9gB/rtw7vZ3J3ENvVKB35x/ILzR/UoY0ETDrEexPcCAwEAAQ==
      connect-properties:
        config.decrypt: true
        config.decrypt.key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJwC0siV5KntGBea3I7m0D5yTChgOn8GI+QB+2dcM2OShu9gB/rtw7vZ3J3ENvVKB35x/ILzR/UoY0ETDrEexPcCAwEAAQ==
      use-ping-method: false
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 3000
          log-slow-sql: true
        config:
          enabled: true
      initial-size: 5
      min-idle: 10
      max-active: 20

  redis:
    host: 1.15.89.164
    #port: 1206
    #password: ENC()
    #cluster:


  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: ENC(GDlPRRvCUTB5UKZYOL/AHIJWdqO1NoNpVsRg9MwBwqhlzaCxwk6JSoLslVY6aRdVLv1pId9tPG8fOTvnu5SKcg==)
    password: ENC(R2ja+nirvuqF/tgBkmW1rUy32oLLu/TCvXsGHgoea3PsnXGdSUZVF2crGuIYkkP3UKbUpWIlQ7bOsSwiDeKwgw==)
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            required: false
        debug: true