server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easyDrive
    username: root
    password: Re4030dd.
    type: com.alibaba.druid.pool.DruidDataSource
