server:
  port: 8080
  servlet:
    session:
      timeout: 30m

uploadPath: /Users/peirong/file/

#mybatis-plus:
  #config-location: classpath:mybatis/mybatis-config.xml
  #mapper-locations: classpath:mybatis/mapper/*.xml
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jasypt:
  encryptor:
    password: REDLXIRGRETFD

PRIVATE_KEY: MIICeQIBADANBgkqhkiG9w0BAQEFAASCAmMwggJfAgEAAoGBANC55yDrRaSNUSoZxf/DwgDGXrtSKoQT4nWnZjT2oqdNmxwiJOzpDAnFXiJSt0PYUVUKlunKHccyGcMPHux3fVAQ7vTAHF+wfvWsa0Rd1If89cNHACGjPqwtpC716TROhUefarFB/uvqhoyR2jgTXuINaOjB6wdnltFuePWvlnmZAgMBAAECgYEAv/Rn0gds6dMo9K31QK1YSnwkfOMoxITA/HCx9z1nArPFVU81ZEdC0e2YD7rAXf2fdrUhaup9DkdOF+xdBR0yuPkycqQUaYNUAPjkwkY/2J5EW3FHOcI+bCTf9u+tNQyWBfZAmJN1ijnnMfp2nOIayMIsStYmVGYsdXf0x86t910CQQDtuObdGzXN9CcX8C0izKt4NTPWxCtwZIWbDJDsyLhM2sd/Kvw3xhyUtaUCNU/Tf3nWrZaWBjaWgFJ8p4BA0GTTAkEA4MZFCtQmiOayGd/H5WWOouEy/lbi55LAyw7Nb1EDVzXCpzKOxi0/5VdGLfIAdhsffipo2vqDhNievU9MxQUUYwJBAKAZG9ojHixTVxTHGw7Jul1dr0jfmsW53UUbxGrDj2OrIBoj7/L8CHmaj8OZ9eXhf0O2aqklDBR13Ze4EycTciMCQQCqWDhMy5jkmYkSKNDyXbPqZqbhr/FINKSdfvtbyFayyhBZ6+vd7r8EzM5n1YZZ+5YzZGqQwdfYXt52c9mnWoEnAkEA1D5rU/rP5LSHJ4//iS8Rcum1fM5dxa/TbFTZQjphTwjtZV1W9+GAiWG7ZsKzuKk5EBs4qjcc7grt0ISbtWknfw==

SECRET_ID: ENC(LX+Dp8PemWOocmh63ZwpRi1zHipZzwTGIk1mzzGXWRGywDlA+6RRvBHuHyqZvzhzVcNOr6jPGKZy1SNoQRSwukBiNjoHGvBBQh1B073w0lU=)
SECRET_KEY: ENC(XOofR17e0jwbkvG6NUq8opazCBSg01OHjYZyD1RhpuEBpWAj5qm5dJzCKC2dWxXOo4rZGpIEIAF9hgIK6hTw5ztBfRhENZRQZbb91mXNUzQ=)

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: ENC(pG1nrvXLMDrgUaSkzIMkWlcxQmhsDY6ONWSaTGRowOHfd4odpBvApftIotiafZ4vq3lSa4BMjkpHXepHZV44v4mgcJsyhEEnpkpHust+SGE=)
    username: ENC(//mZsqJl4h1VXp5tYIwnNC9rqPUIGJqAILJOYE5W+1usk0l/JbTMvvh7p0ldwhXv)
    password: T34X7i/AESfBBbvyrpRTCJFTY7gkpWqfKaPckRPySx80rg5nEZ7SIJgmM1EgXrzzv1UE5UUaytumgGkUZkpzkA==
    druid:
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJwC0siV5KntGBea3I7m0D5yTChgOn8GI+QB+2dcM2OShu9gB/rtw7vZ3J3ENvVKB35x/ILzR/UoY0ETDrEexPcCAwEAAQ==
      connect-properties:
        config.decrypt: true
        config.decrypt.key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJwC0siV5KntGBea3I7m0D5yTChgOn8GI+QB+2dcM2OShu9gB/rtw7vZ3J3ENvVKB35x/ILzR/UoY0ETDrEexPcCAwEAAQ==
      use-ping-method: false
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 3000
          log-slow-sql: true
        config:
          enabled: true
      initial-size: 5
      min-idle: 10
      max-active: 20

  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: ENC(GDlPRRvCUTB5UKZYOL/AHIJWdqO1NoNpVsRg9MwBwqhlzaCxwk6JSoLslVY6aRdVLv1pId9tPG8fOTvnu5SKcg==)
    password: ENC(R2ja+nirvuqF/tgBkmW1rUy32oLLu/TCvXsGHgoea3PsnXGdSUZVF2crGuIYkkP3UKbUpWIlQ7bOsSwiDeKwgw==)
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            required: false
        debug: true